# Generated by Django 5.2.11 on 2026-03-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_moviereview_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='title',
            field=models.TextField(default='Reseña'),
        ),
    ]
